 CREATE TABLE "TJOEUNIT"."INJECTION_11" 
   (	"IDX" NUMBER(*,0) NOT NULL ENABLE, 
	"PATIENTIDX" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MEDICINE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DOSAGE" VARCHAR2(20 BYTE), 
	"ROUTE" VARCHAR2(20 BYTE), 
	"INJECTTIME" VARCHAR2(20 BYTE), 
	"WRITEDATE" TIMESTAMP (6) DEFAULT sysdate, 
	"EMPLOYEEIDX" NUMBER(*,0) NOT NULL ENABLE, 
	"REALTIME" VARCHAR2(20 BYTE), 
	"INJECTION" CHAR(1 BYTE) DEFAULT 'N', 
	"EMPLOYEENAME" VARCHAR2(20 BYTE), 
	 CONSTRAINT "INJECTION_11_PK" PRIMARY KEY ("IDX")
   );
    
delete from INJECTION_11;
drop SEQUENCE INJECTION_11_idx_seq;
create SEQUENCE INJECTION_11_idx_seq;


SELECT * FROM INJECTION_11;
DROP TABLE INJECTION_11;


insert into INJECTION_11 (idx, patientIdx, name, medicine, dosage, route, injectTime, realTime, injection, employeeIdx, employeename, writeDate)
values (INJECTION_11_idx_seq.nextval, 100007, '구창모', 'NS 0.9% [수액제]', '3000ml', 'IV', '24h', '10A', 'Y', 2101, '정호석', sysdate-2);
 
 